# Generated by Django 3.2 on 2021-05-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0003_auto_20210505_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='account',
        ),
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farsys.account'),
        ),
    ]
