# Generated by Django 3.2 on 2021-05-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0004_auto_20210517_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='farsys.account'),
            preserve_default=False,
        ),
    ]
