# Generated by Django 3.2 on 2021-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0005_attribute_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editable',
            field=models.BooleanField(null=True),
        ),
    ]
