# Generated by Django 3.2 on 2021-05-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0008_product_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
    ]
