# Generated by Django 3.2 on 2021-06-09 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0010_auto_20210608_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='farsys.attribute'),
        ),
    ]
