# Generated by Django 3.2 on 2021-06-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farsys', '0011_alter_purchaseitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
